name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        env:
          EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
          PRIVATE_KEY_FILE: ${{ secrets.PRIVATE_KEY_FILE }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh-keyscan -H ${{env.EC2_INSTANCE_IP}} >> ~/.ssh/known_hosts
          ssh -i ${{env.PRIVATE_KEY_FILE}} ${{env.EC2_USER}}@${{env.EC2_INSTANCE_IP}} 'cd Student-Portal && sudo su && git pull && npm install && pm2 restart portal-server'

