name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:           
      - name: Deploy to EC2        
        run: |
          cd ~/Student-Portal
          git pull
          npm install
          sudo pm2 restart portal-server
         
      
