name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:           
      - name: Deploy to EC2        
        run: |
          cd ~/Student-Portal
          sudo su
          git pull
          npm install
          pm2 restart portal-server
         
      
